bagusrin_summarizer_analyze:
    path:     /analyze
    defaults: { _controller: BagusrinSummarizerBundle:Default:analyze }
    requirements:
        _method: POST
bagusrin_summarizer_analyze_url:
    path:     /analyzeUrl
    defaults: { _controller: BagusrinSummarizerBundle:Default:analyzeUrl }
    requirements:
        _method: POST
